### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [Craft4Coffee/dasmotos#5]
**GRADE**: Needs Improvement

**SUMMARY**: Great start on this project. With a couple tweaks the site will be looking great! Good idea to use divs to help structure the content on the page, just make sure to keep your indentation consistent inside of them to help keep your code as readable as possible. 

Behind the scenes, it is very important to keep in mind DRY principles. Avoid setting the same bits of styling many times for similarly styled elements wherever possible. Also, be sure to use relative file paths to link to all your local resources, including the css file. 

As a next step, try changing up the link to your css to make sure that link stays healthy no matter where the project is stored.

Have fun and keep up the good work!

**Comment by Craft4Coffee** [comment]
Thank you! I will make the appropriate updates.
